dependencies: ["package.json", "package-lock.json"]
CI/CD: .github
build: ["nx.json", "project.json", "angular.json", ".releaserc"]
documentation: docs
docker: Dockerfile
combine-api: app/combine-api
runBiosimulations: apps/dispatch
BioSimulations: apps/platform
# BioSimulationsBrowse: apps/projex
BioSimulators: apps/simulators
BioSimulations-API: ["apps/api" , "libs/api"]
BioSimulators-API: apps/simulators-api
ontologies: libs/shared/ontology
datamodel: libs/datamodel
messaging: libs/messages
simulation-service: apps/dispatch-service
testing: ["*.spec.ts"]
ui: ["*.component.ts", "*.scss", "*.html"]
