version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/biosimulations"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  target-branch: dev
  labels:
  - dependencies
  
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
