site_name: BioSimulations Documentation
site_url: https://docs.biosimulations.org/
docs_dir: docs
repo_url: https://github.com/BioSimulations/Biosimulations
edit_uri: blob/dev/docs/
theme:
  name: material
  logo: assets/images/safari-pinned-tab.svg
  favicon: assets/icons/favicon.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: biosimulations-dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
 
plugins:
  - git-revision-date
  - search
extra_css:
  - stylesheets/theme.css
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bio_sims
      name: BioSimulations on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/BioSimulations/Biosimulations
      name: BioSimulations on Github      
copyright: Copyright &copy; 2019 - 2021 BioSimulations Team
nav:
  - Home: README.md
    
  - "About":
    - License: License.md
    - "Privacy Policy": PRIVACY_POLICY.md
    - "Terms of Service": TERMS_OF_SERVICE.md
      
  - "User Guide":
      - FAQ: FAQ.md
      - Help: Help.md
        
  - "Development Guide": 
    - Contributing: CONTRIBUTING.md
    - Code of Conduct: CODE_OF_CONDUCT.md
      
    