---
openapi: 3.0.0
info:
  title: BioSimulations COMBINE service
  version: "0.1"
  description: "Endpoints for working with COMBINE/OMEX archives and model (e.g.,\
    \ SBML) and simulation (e.g., SED-ML) files that they typically contain.\n\nNote,\
    \ this API may change significantly in the future."
  contact:
    name: BioSimulations Team
    url: https://biosimulations.org
    email: info@biosimulations.org
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
paths:
  /combine/sedml-output-specs:
    get:
      tags:
      - COMBINE
      - OMEX
      - SED-ML
      parameters:
      - name: archiveUrl
        description: |-
          URL for a COMBINE/OMEX archive that contains one or more SED-ML files that describe one or more plots.

          The SED-ML files should be defined in the manifest of the the COMBINE/OMEX archive with a format attribute such as  "http://identifiers.org/combine.specifications/sed-ml" or "http://identifiers.org/combine.specifications/sed-ml.level-1.version-3".
        schema:
          type: string
        in: query
        required: true
      responses:
        "400":
          content:
            application/json: {}
          description: Unable to get specs for COMBINE/OMEX archive because URL is
            unavailable or URL is not a valid COMBINE/OMEX archive.
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CombineArchive'
          description: Specifications of the plots in the SED-ML files in the COMBINE/OMEX
            archive.
      operationId: handlers.get_sedml_output_specs_for_combine_archive
      summary: Get the specifications of the plots in SED-ML files in a COMBINE/OMEX
        archive
      description: Get the specifications of the outputs in SED-ML files in a COMBINE/OMEX
        archive
  /combine/create:
    post:
      requestBody:
        description: Specifiations for the COMBINE/OMEX archive and its contents (specifications
          of the SED-ML file and model file(s)).
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/SeparateFileUpload'
        required: true
      tags:
      - COMBINE
      - OMEX
      - SED-ML
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: URL for the created COMBINE/OMEX archive.
      operationId: handlers.create_combine_archive
      summary: Assemble a COMBINE/OMEX archive from model files and specifications
        of a SED-ML document.
      description: Assemble a COMBINE/OMEX archive from model files and specifications
        of a SED-ML document.
  /sed-ml/get-data-generators-for-model:
    post:
      requestBody:
        description: Model file
        content:
          multipart/form-data: {}
        required: true
      tags:
      - SED-ML
      - SBML
      parameters:
      - examples:
          SBML:
            value: urn:sedml:language:sbml
        name: modelFormat
        description: SED URN for model format
        schema:
          enum:
          - urn:sedml:language:sbml
          type: string
        in: query
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SedVariable'
          description: Possible observables of a model as a list of SED data generators
        "400": {}
      operationId: get_data_generators_for_model
      summary: Get the possible observables of a model as a list of SED variables
components:
  schemas:
    SedPlot2D:
      description: Specifications for a 2D SED plot.
      required:
      - id
      - curves
      - xScale
      - yScale
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        curves:
          description: List of the curves of the plot (tuples of x and y data).
          type: array
          items:
            $ref: '#/components/schemas/SedCurve'
        xScale:
          $ref: '#/components/schemas/SedAxisScale'
          description: Scale of the x axis.
        yScale:
          $ref: '#/components/schemas/SedAxisScale'
          description: Scale of the y axis.
        _type:
          description: Type of the plot.
          enum:
          - SedPlot2D
          type: string
    SedPlot3D:
      description: Specifications for a 3D surface plot.
      required:
      - id
      - surfaces
      - xScale
      - yScale
      - zScale
      - _type
      type: object
      properties:
        id:
          description: Unique id within its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        surfaces:
          $ref: '#/components/schemas/SedSurface'
          description: "List of surfaces (tuples of x, y, and z data)."
        xScale:
          $ref: '#/components/schemas/SedAxisScale'
          description: Scale of the x axis.
        yScale:
          $ref: '#/components/schemas/SedAxisScale'
          description: Scale of the y axis.
        zScale:
          $ref: '#/components/schemas/SedAxisScale'
          description: Scale of the z axis.
        _type:
          description: Type of the output.
          enum:
          - SedPlot3D
          type: string
    SedCurve:
      description: Curve of a 2D SED plot
      required:
      - id
      - xDataGenerator
      - yDataGenerator
      - _type
      type: object
      properties:
        id:
          description: Unique identifier with its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        xDataGenerator:
          $ref: '#/components/schemas/SedDataGenerator'
          description: Identifier of the data generator for the x data of the curve.
        yDataGenerator:
          $ref: '#/components/schemas/SedDataGenerator'
          description: Identifier of the data generator for the y data of the curve.
        _type:
          description: Type.
          enum:
          - SedCurve
          type: string
    SedSurface:
      description: A surface a 3D plot.
      required:
      - id
      - xDataGenerator
      - yDataGenerator
      - zDataGenerator
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        xDataGenerator:
          $ref: '#/components/schemas/SedDataGenerator'
          description: Identifier of the data generator for the x data of the surface.
        yDataGenerator:
          $ref: '#/components/schemas/SedDataGenerator'
          description: Identifier of the data generator for the y data of the surface.
        zDataGenerator:
          $ref: '#/components/schemas/SedDataGenerator'
          description: Identifier of the data generator for the z data of the surface.
        _type:
          description: Type.
          enum:
          - SedSurface
          type: string
    SedDataGenerator:
      description: Data generator for SED report or plot.
      required:
      - id
      - math
      - variables
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        variables:
          description: Variables.
          type: array
          items:
            $ref: '#/components/schemas/SedVariable'
        math:
          description: Mathematical expression for its value.
          type: string
        _resultsDataSetId:
          $ref: '#/components/schemas/BioSimulationsDataSetResultsId'
          description: Id of the results in the runBioSimulations database of simulation
            results.
        _type:
          description: Type.
          enum:
          - SedDataGenerator
          type: string
    SedDocument:
      description: A SED document.
      required:
      - outputs
      - level
      - version
      - models
      - simulations
      - tasks
      - dataGenerators
      - _type
      type: object
      properties:
        outputs:
          description: Outputs.
          type: array
          items:
            $ref: '#/components/schemas/SedOutput'
        level:
          description: Level.
          type: integer
        version:
          description: Version.
          type: integer
        models:
          description: Models.
          type: array
          items:
            $ref: '#/components/schemas/SedModel'
        simulations:
          description: Simulations.
          type: array
          items:
            $ref: '#/components/schemas/SedSimulation'
        tasks:
          description: Tasks.
          type: array
          items:
            $ref: '#/components/schemas/SedTask'
        dataGenerators:
          description: Data generators.
          type: array
          items:
            $ref: '#/components/schemas/SedDataGenerator'
        _type:
          description: Type.
          enum:
          - SedDocument
          type: string
      example:
        level: 1
        version: 4
        models: []
        simulations: []
        tasks: []
        dataGenerators: []
        outputs: []
    SedReport:
      description: A SED report.
      required:
      - id
      - _type
      - dataSets
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        _type:
          description: Type of the output.
          enum:
          - SedReport
          type: string
        name:
          description: Brief description.
          type: string
        dataSets:
          description: List of the data sets of the report (rows of the report).
          type: array
          items:
            $ref: '#/components/schemas/SedDataSet'
    SedDataSet:
      description: A SED data set
      required:
      - id
      - dataGenerator
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        label:
          description: Brief description
          type: string
        name:
          description: Brief description.
          type: string
        dataGenerator:
          $ref: '#/components/schemas/SedDataGenerator'
          description: Generator which provides the data for the data set.
        _type:
          description: Type.
          enum:
          - SedDataSet
          type: string
    CombineArchive:
      description: A COMBINE/OMEX archive.
      required:
      - contents
      - _type
      type: object
      properties:
        contents:
          description: The content of the archive
          type: array
          items:
            $ref: '#/components/schemas/CombineArchiveContent'
        _type:
          description: Type.
          enum:
          - CombineArchive
          type: string
    CombineArchiveContent:
      description: Content item of a COMBINE/OMEX archive.
      required:
      - location
      - format
      - master
      - _type
      type: object
      properties:
        location:
          $ref: '#/components/schemas/CombineArchiveLocation'
          description: Location within its parent COMBINE/OMEX archive.
        format:
          description: Format.
          type: string
        master:
          description: ""
          type: boolean
        _type:
          description: Type.
          enum:
          - CombineArchiveContent
          type: string
    CombineArchiveLocation:
      description: Location of an item in a COMBINE/OMEX archive and its value.
      required:
      - path
      - value
      - _type
      type: object
      properties:
        path:
          description: Path within a COMBINE/OMEX archive.
          type: string
        value:
          $ref: '#/components/schemas/CombineArchiveLocationValue'
          description: Value of the content item of the COMBINE/OMEX archive.
        _type:
          description: Type.
          enum:
          - CombineArchiveLocation
          type: string
    SedModel:
      description: A SED model.
      required:
      - id
      - language
      - source
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        language:
          description: "Format (e.g., BNGL, SBML)."
          type: string
        source:
          description: Location of the file for the model.
          type: string
        _type:
          description: Type.
          enum:
          - SedModel
          type: string
      example:
        id: model_1
        name: Model 1
        language: urn:sedml:language:sbml
        source: model_1.xml
    SedSimulation:
      oneOf:
      - type: object
      - $ref: '#/components/schemas/SedSteadyStateSimulation'
      - $ref: '#/components/schemas/SedUniformTimeCourseSimulation'
      - $ref: '#/components/schemas/SedOneStepSimulation'
      description: A SED simulation.
      type: object
    SedTask:
      description: A SED task.
      required:
      - id
      - model
      - simulation
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within is parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        model:
          $ref: '#/components/schemas/SedModel'
          description: Model.
        simulation:
          $ref: '#/components/schemas/SedSimulation'
          description: Simulation
        _type:
          description: Type.
          enum:
          - SedTask
          type: string
    SedUniformTimeCourseSimulation:
      description: A SED uniform time course simulation.
      required:
      - id
      - name
      - _type
      - initialTime
      - outputStartTime
      - outputEndTime
      - numberOfSteps
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        _type:
          description: Type of the simulation.
          enum:
          - SedUniformTimeCourseSimulation
          type: string
        initialTime:
          description: Initial time.
          type: number
        outputStartTime:
          description: Output start time.
          type: number
        outputEndTime:
          description: Output end time.
          type: number
        numberOfSteps:
          description: Number of steps.
          type: integer
    SedSteadyStateSimulation:
      description: A SED steady state simulation.
      required:
      - id
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        _type:
          description: Type of the simulation.
          enum:
          - SedSteadyStateSimulation
          type: string
    SedOneStepSimulation:
      description: A SED one step simulation.
      required:
      - id
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        _type:
          description: Type of the simulation.
          enum:
          - SedOneStepSimulation
          type: string
        name:
          description: Brief description.
          type: string
        step:
          description: Step size.
          type: number
    SedVariable:
      description: A SED variable.
      required:
      - id
      - task
      - _type
      type: object
      properties:
        id:
          description: Unique identifier within its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        task:
          $ref: '#/components/schemas/SedTask'
          description: Task.
        target:
          description: "Target within a model (e.g., of a dependent variable such\
            \ as the concentration of a species)."
          type: string
        symbol:
          description: "Symbol (e.g., for an independent variable such as time)."
          type: string
        _type:
          description: Type.
          enum:
          - SedVariable
          type: string
    SeparateFileUpload:
      description: The two files uploaded in creating a combine archive
      required:
      - modelFile
      - simulationFile
      type: object
      properties:
        modelFile:
          format: binary
          description: The file for the model in one of the supported formats
          type: string
        simulationFile:
          format: binary
          description: The simulation specification in one of the accepted formats
            (sedml)
          type: string
    SedRepeatedTask:
      description: A SED repeated task.
      required:
      - id
      - _type
      type: object
      properties:
        id:
          description: Unique identifiers with its parent SED document.
          type: string
        name:
          description: Brief description.
          type: string
        _type:
          description: Type.
          enum:
          - SedRepeatedTask
          type: string
    SedAxisScale:
      description: ""
      enum:
      - log
      - linear
      type: string
    BioSimulationsDataSetResultsId:
      description: Id of the results of a data set.
      type: string
    SedOutput:
      oneOf:
      - $ref: '#/components/schemas/SedPlot2D'
      - $ref: '#/components/schemas/SedPlot3D'
      - $ref: '#/components/schemas/SedReport'
      discriminator:
        propertyName: _type
      description: An output of a SED document.
      type: object
    SedAbstractTask:
      oneOf:
      - $ref: '#/components/schemas/SedTask'
      - $ref: '#/components/schemas/SedRepeatedTask'
      discriminator:
        propertyName: _type
      description: A SED abstract task.
      type: object
    CombineArchiveLocationValue:
      oneOf:
      - $ref: '#/components/schemas/SedDocument'
      - $ref: '#/components/schemas/CombineArchiveContentFile'
      discriminator:
        propertyName: _type
      description: The value of a location of a COMBINE/OMEX archive.
      type: object
    CombineArchiveContentFile:
      description: File
      required:
      - _type
      - filename
      type: object
      properties:
        _type:
          description: Type.
          enum:
          - CombineArchiveContentFile
          type: string
        filename:
          description: Name of file on the submitter's machine
          type: string
  responses:
    "404":
      content:
        application/json: {}
      description: The selected resource was not found
