contact_links:
  - name: Request a model format, framework, algorithm, or simulator
    url: https://github.com/biosimulators/Biosimulators/issues/new/choose
    about: Please direct requests for model formats, frameworks, algorithms, and simulation tools to BioSimulators
