apiVersion: apps/v1
kind: Deployment
metadata:
  name: biosimulations-dispatch-api
  labels:
    app: biosimulations-nats
  namespace: default
spec:
    selector:
        matchLabels:
          app: biosimulations-dispatch-api
    replicas: 1
    template:
      metadata:
        labels:
          app: biosimulations-dispatch-api
      spec:
        containers:
        - name: biosimulations-dispatch-api
          image: crbm/biosimulations-dispatch-api:dev
          ports:
            - containerPort: 3333
# TODO: Move this ENV to config file          
          env:
            - name: "FILE_STORAGE"
              value: "/sharedFiles"
          volumeMounts:
            - mountPath: "/app/secret"
              name: secret
              readOnly: true
        volumes:
          - name: secret
            secret:
              secretName: dispatch-api-secrets-h894ddfb62
---
  apiVersion: v1
  kind: Service
  metadata:
    name: biosimulations-dispatch-api
    labels:
      app: biosimulations-dispatch-api
    namespace: default
  spec:
    type: NodePort
    ports:
    - port: 3333
      targetPort: 3333
      protocol: TCP
      nodePort: 30333
      name: dispatch-api
    selector:
      app: biosimulations-dispatch-api
