networks:
  biosimulations-dev-net:
    driver: bridge

services:
  # -- middleware services --
  nats:
    image: nats:latest
    restart: unless-stopped
    ports: 
      - "4222:4222"
    networks:
      - biosimulations-dev-net

  redis-primary:
    image: redis:latest
    restart: unless-stopped
    ports: 
      - "6379:6379"
    networks:
      - biosimulations-dev-net

  # -- internal services --
  api: 
    platform: linux/amd64
    build: 
      context: . 
      dockerfile: ./Dockerfile  # ./api.devcontainer/Dockerfile
      args: 
        VARIANT: 18-bullseye
        USER_UID: 504  # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_GID: 20
    volumes:
    - ..:/workspace  # :cached
    ports:
      - "4444:4444"
    user: "504"
    command: sleep infinity  # Overrides default command so things don't shut down after the process ends.
    networks:
      - biosimulations-dev-net
    depends_on:
      - nats
      - redis-primary
      - dispatch-service
      - combine-api
      # - mongo
    env_file:
      - ../config/config.env
  dispatch-service: 
    platform: linux/amd64
    build: 
      context: . 
      dockerfile: ./Dockerfile  # ./dispatch-service.devcontainer/Dockerfile
      args: 
        VARIANT: 18-bullseye
        USER_UID: 504
        USER_GID: 20
    volumes:
    - ..:/workspace  # cached
    user: "504"
    command: sleep infinity   
    networks:
      - biosimulations-dev-net
    depends_on:
      - nats
      - redis-primary
      # - mongo
    env_file:
      - ../config/config.env
  combine-api: 
    platform: linux/amd64
    build: 
      context: ../apps/combine-api 
      dockerfile: ../../.devcontainer/combine-api.devcontainer/Dockerfile  # ./combine-api.devcontainer/Dockerfile
      args: 
        USER_UID: 504 
        USER_GID: 20
        VARIANT: "3.10-bullseye"
        POETRY_VERSION: "1.8.4"
    volumes:
      - ..:/workspace  # :cached
    ports:
      - "3333:3333"
    user: "vscode"
    command: sleep infinity   
    networks:
      - biosimulations-dev-net
    depends_on:
      - nats
      - redis-primary
      # - mongo

  # -- front-end webapp --
  platform: 
    platform: linux/amd64
    build: 
      context: . 
      dockerfile: ./Dockerfile  # ./platform.devcontainer/Dockerfile
      args: 
        VARIANT: 18-bullseye
        USER_UID: 504 
        USER_GID: 20
    volumes:
    - ..:/workspace  # :cached
    ports:
      - "4200:4200"
    user: "504"
    command: sleep infinity   
    networks:
      - biosimulations-dev-net
    depends_on:
      - api
