#############
### base ###
#############
FROM ghcr.io/devcontainers/templates/python:10-bullseye as base

# Set up the working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update -y && apt-get install --no-install-recommends -y \
    g++ \
    libatlas-base-dev \
    swig \
    perl \
    tar \
    wget \
    r-base-dev \
    build-essential \
    gcc \
    gfortran \
    libblas-dev \
    libcurl4-openssl-dev \
    libgit2-dev \
    liblapack-dev \
    libssl-dev \
    libxml2 \
    libxml2-dev \
    libglpk-dev \
    default-jre \
    cmake \
    xvfb \
    libfreetype6 \
    libxml2 \
    libncurses5 \
    libx11-dev \
    libc6-dev \
    libx11-6 \
    libc6 \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY pyproject.toml poetry.lock /app/
RUN curl -sSL https://install.python-poetry.org | python3 - \
    && poetry config virtualenvs.create false \
    && poetry install --no-dev

# Copy the application code
COPY . /app

# Set up the entrypoint
CMD ["poetry", "run", "gunicorn", \
    "--bind", "0.0.0.0:3333", \
    "combine_api.app:app", \
    "--workers", "2", \
    "--threads", "4", \
    "--worker-class", "gthread", \
    "--max-requests", "1000", \
    "--timeout", "30", \
    "--keep-alive", "5", \
    "--worker-tmp-dir", "/dev/shm", \
    "--log-level", "debug", \
    "--log-file=-"]