site_name: BioSimulations documentation
site_url: https://docs.biosimulations.org/
docs_dir: .
repo_url: https://github.com/biosimulations/biosimulations
edit_uri: blob/dev/docs/
theme:
  name: material
  logo: assets/logos/logo.svg
  favicon: assets/icons/favicon.ico
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: '(prefers-color-scheme: biosimulations-dark)'
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

plugins:
  - search
  - redirects:
      redirect_maps:
        'repositories/bigg.md': 'https://biosimulations.github.io/biosimulations-bigg'
        'privacy.md': 'about/privacy.md'
  - git-revision-date
  - same-dir
  - awesome-pages

extra_css:
  - stylesheets/theme.css
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bio_sims
      name: BioSimulations on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/biosimulations/biosimulations
      name: BioSimulations on Github
copyright: Copyright &copy; 2019 - 2021 BioSimulations Team
