name: Auto approve robots
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened 
      - labeled 
      - unlabeled
      - edited
jobs:
  approve-dependabot:
    name: Auto-approve dependabot PRs
    if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{secrets.GITHUB_TOKEN }}"

  approve-daemon:
    name: Auto-approve daemon PRs
    if: github.actor == 'biosimulations-daemon'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{secrets.GITHUB_TOKEN }}"
