name: Build, lint, and test
on:
  workflow_call:
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true
    inputs:
      env:
        required: false
        type: string
        default: "dev"
      name:
        required: false
        type: string
        default: "CI"
      upload:
        required: false
        type: boolean
        default: true
      affectedOnly:
        required: false
        type: boolean
        default: true

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'dev'

      - name: Set Branch Environment
        if: ${{ github.event_name == 'push' }}
        run: echo NX_BRANCH=$GITHUB_REF >> $GITHUB_ENV

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install Poetry
        run: pipx install poetry==1.4.0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Flake8
        run: |
          python -m pip install flake8

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '18'

      - name: Print node and npm versions
        run: |
          node --version
          npm --version

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1
        with:
          command: npm ci

      - run: npx nx-cloud start-ci-run
        name: Start CI Run
        if: always()

      - name: Lint Build Test Affected
        if:  ${{inputs.affectedOnly}}
        run: |
          npx nx affected --target=lint --parallel
          npx nx affected --target=build --prod --parallel
          npx nx affected --target=test --parallel
      - name: Lint Build Test All
        if: ${{!inputs.affectedOnly}}
        run: |
          npx nx run-many --all --target=lint --parallel
          npx nx run-many --all --target=build --prod --parallel
          npx nx run-many --all --target=test --parallel
      - name: Stop CI run
        run: npx nx-cloud stop-all-agents
        if:  always()

      - name: Upload builds
        uses: actions/upload-artifact@v2
        if: ${{inputs.upload}}
        with:
          name: ${{inputs.name}}
          path: dist/
          retention-days: 5
          if-no-files-found: ${{ fromJSON('["warn", "error"]')[!inputs.affectedOnly]}}

  agents:
    runs-on: ubuntu-latest
    name: Worker Node
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ]
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install Poetry
        run: pipx install poetry==1.4.0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"

      - name: Install Flake8
        run: |
          python -m pip install flake8

      - uses: actions/setup-node@v3.3.0
        with:
          node-version: '18'

      - name: Print node and npm versions
        run: |
          node --version
          npm --version

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: 'ghcr.io'
          username: "${{ secrets.GHCR_USERNAME }}"
          password: "${{ secrets.GHCR_TOKEN }}"

      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
