name: Build sitemap(s) for app(s)

on:
  schedule:
    - cron: '0 0 * * 0' # weekly
  workflow_call:
    inputs:
      apps:
        description: 'Comma-separated list of the names of app(s) to build sitemaps for; default: build a sitemap for each app'
        required: false
        default: ''
        type: string
    secrets:
      GH_ACCESS_TOKEN:
        required: true
      GPG_PRIVATE_KEY:
        required: true

  workflow_dispatch:
    inputs:
      apps:
        description: 'Comma-separated list of the names of app(s) to build sitemaps for; default: build a sitemap for each app'
        required: false
        default: ''

env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_ACCESS_TOKEN}}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install sitemap build utility
        run: python3 -m pip install -r ${GITHUB_WORKSPACE}/tools/build-sitemaps/requirements.txt

      - name: Build sitemap(s)
        run: python3 ${GITHUB_WORKSPACE}/tools/build-sitemaps ${{ github.event.inputs.apps }}

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit Changes
        uses: EndBug/add-and-commit@v8.0.2
        with:
          author_name: BioSimulations-Daemon
          author_email: biosimulationsdaemon@gmail.com
          branch: dev
          commit: --signoff
          pull: --rebase --autostash
          message: 'chore: update sitemaps [skip ci]'

        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}} # Leave this line unchanged
