name: Cancel old workflow runs
on: [push]
jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: cd.yml, ci.yml, dependencyLicense.yml
          access_token: ${{ github.token }}
