name: Cancel workflows after PRs closed
on:
  pull_request:
    types: [closed]
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}
jobs:
  cleanup:
    name: 'Cancel workflows after PR closed'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Cancel build runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          ignore_sha: true
          workflow_id: cd.yml, ci.yml, dependencyLicense.yml, codeql-analysis.yml, ossar-analysis.yml
          access_token: ${{ github.token }}
