name: Continuous integration
on:
  push:
    branches: [dev]
    paths-ignore:
      - "docs/**"
      - "tools/**"
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}
jobs:
  Format:
    uses: ./.github/workflows/format.yml
    secrets:
       GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
       GH_ACCESS_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
    with:
      branch: dev

  DependencyLicense:
    uses: ./.github/workflows/dependencyLicense.yml
    secrets:
       GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
       GH_ACCESS_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}
    with:
      branch: dev

#  UpdateSitemaps:
#    uses: ./.github/workflows/buildSitemaps.yml
#    secrets:
#       GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
#       GH_ACCESS_TOKEN: ${{secrets.GH_ACCESS_TOKEN}}

  Release:
    # needs: [DependencyLicense, Format, UpdateSitemaps]
    needs: [DependencyLicense, Format]
    uses: ./.github/workflows/release.yml
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
      NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
    with:
      branch: dev

