# see https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: Continuous Integration
on:
  pull_request:
    branches:
      - dev
    paths:
      - "docs/**"
      - "tools/**"
      - ".all-contributorsrc"
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '

  Docker:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required" '
