name: Continuous Integration
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - docker-ci
jobs:
  CI:
    uses: biosimulations/biosimulations/.github/workflows/buildLintTest.yml@docker-ci

  Docker:
    uses: biosimulations/biosimulations/.github/workflows/docker.yml@docker-ci
    secrets:
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
      GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}
    with:
      push: true


