name: Continuous Integration
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "docs/**"
      - "tools/**"
      - ".all-contributorsrc"
  pull_request:
jobs:
  main:
    uses: biosimulations/biosimulations/.github/workflows/buildLintTest.yml@dev
