name: Continuous Integration
on:
  push:
    branches:
      - dev
    paths-ignore:
      - "docs/**"
      - "tools/**"
      - ".all-contributorsrc"
  pull_request:
jobs:
  CI:
    uses: biosimulations/biosimulations/.github/workflows/buildLintTest.yml@dev
  Docker:
    uses: biosimulations/biosimulations/.github/workflows/docker.yml@dev
    secrets:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
      GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}
    with:
      push: true

