name: Continuous Integration
on:
  pull_request:
    branches:
      - dev
jobs:
  CI:
    uses: biosimulations/biosimulations/.github/workflows/buildLintTest.yml@dev
    secrets:
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
      GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}
    with:
      push: true

  Docker:
    uses: biosimulations/biosimulations/.github/workflows/docker.yml@dev
    secrets:
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
      GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}
    with:
      push: true

