name: Validate pull request
on:
  pull_request:
    branches:
      - dev
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}

jobs:
  CI:
    uses: ./.github/workflows/buildLintTest.yml
    secrets:
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
      GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}

  Docker:
    uses: ./.github/workflows/docker.yml
    secrets:
      GHCR_USERNAME: ${{secrets.GHCR_USERNAME}}
      GHCR_TOKEN: ${{secrets.GHCR_TOKEN}}
    with:
      push: true
