name: Lint, test, build, containerize, and deploy apps

on:
  - push
  - pull_request

jobs:
  get-affected-apps:
    name: Determine affected apps
    runs-on: ubuntu-latest
    outputs:
      apps: ${{ steps.get-affected-apps.outputs.apps }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
            then
              echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
           else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Install Nrwl CLI
        working-directory: ./biosimulations
        run: npm install -g @nrwl/cli

      - name: Install apps
        working-directory: ./biosimulations
        run: npm ci

      - id: get-affected-apps
        name: Determine affected apps
        run: |
          mapfile -d " " -t appsArr < <( nx affected:apps --base=$NX_BASE --plain )
          appsArr[-1]=$(echo "${appsArr[-1]}" | xargs)
          appsJson=$(printf '%s\n' "${appsArr[@]}" | jq -R . | jq -s . | tr -d '\n')
          appsJsonEscaped=$(echo $appsJson | sed 's/"/\\"/g')
          echo "::set-output name=apps::$appsJsonEscaped"

  lint:
    name: Lint libraries and apps
    runs-on: ubuntu-latest

    needs: get-affected-apps
    strategy:
      matrix:
        app: ${{ fromJson(needs.get-affected-apps.outputs.apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
            then
              echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
           else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Install Nrwl CLI
        working-directory: ./biosimulations
        run: npm install -g @nrwl/cli

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./biosimulations
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}

      - name: Lint libraries and apps
        working-directory: ./biosimulations
        run: ng run ${{ matrix.app }}:lint --base=$NX_BASE

  build:
    name: Build apps
    runs-on: ubuntu-latest

    needs: get-affected-apps
    strategy:
      matrix:
        app: ${{ fromJson(needs.get-affected-apps.outputs.apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
            then
              echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
           else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Install Nrwl CLI
        working-directory: ./biosimulations
        run: npm install -g @nrwl/cli

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./biosimulations
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}

      - name: Build apps
        working-directory: ./biosimulations
        run: ng run ${{ matrix.app }}:build --base=$NX_BASE --prod

  test:
    name: Test libraries and apps
    runs-on: ubuntu-latest

    needs: get-affected-apps
    strategy:
      matrix:
        app: ${{ fromJson(needs.get-affected-apps.outputs.apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
            then
              echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
           else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Install Nrwl CLI
        working-directory: ./biosimulations
        run: npm install -g @nrwl/cli

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./biosimulations
        run: npm ci

      - name: Cache Angular and NX dependencies
        uses: actions/cache@v2
        with:
          path: node_modules/.cache
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}

      - name: Test libraries and apps
        working-directory: ./biosimulations
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
          API_AUDIENCE: ${{ secrets.API_AUDIENCE }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MANAGEMENT_DOMAIN: ${{ secrets.MANAGEMENT_DOMAIN }}
          MANAGEMENT_ID: ${{ secrets.MANAGEMENT_ID }}
          MANAGEMENT_SECRET: ${{ secrets.MANAGEMENT_SECRET }}
        run: ng run ${{ matrix.app }}:test --base=$NX_BASE --code-coverage

      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

  build-push-deploy-docker-images:
    name: Build, push, and deploy Docker images for apps
    runs-on: ubuntu-latest

    needs: get-affected-apps
    strategy:
      matrix:
        app: ${{ fromJson(needs.get-affected-apps.outputs.apps) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Configure base commit
        run: |
          if [[ $GITHUB_BASE_REF ]]
            then
              echo NX_BASE=origin/$GITHUB_BASE_REF >>$GITHUB_ENV
           else
            echo NX_BASE=origin/deploy >>$GITHUB_ENV
          fi

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Install Nrwl CLI
        working-directory: ./biosimulations
        run: npm install -g @nrwl/cli

      - name: Install apps
        working-directory: ./biosimulations
        run: npm ci

      - name: Install Google Cloud CLI
        run: |
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          sudo apt-get update -y
          sudo apt-get install -y curl apt-transport-https ca-certificates gnupg
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt-get update -y
          sudo apt-get install -y google-cloud-sdk

      - name: Kubernetes CLI
        run: |
          sudo apt-get update -y
          sudo apt-get install -y apt-transport-https gnupg2 curl
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
          sudo apt-get update -y
          sudo apt-get install -y kubectl

      - name: Build, push, and deploy Docker images
        working-directory: ./biosimulations
        env:
            GHCR_USERNAME: "${{ secrets.GHCR_USERNAME }}"
            GHCR_TOKEN: "${{ secrets.GHCR_TOKEN }}"
            DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
            DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
            GCLOUD_EMAIL: "${{ secrets.GCLOUD_EMAIL }}"
            GCLOUD_KEY: "${{ secrets.GCLOUD_KEY }}"
        run: ./tools/build-push-deploy-docker-image -a ${{ matrix.app }}
