name: Close stale todo issues
on:
  schedule:
    - cron: '0 0 * * 0' # weekly
  workflow_dispatch:
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}

jobs:
  close-issues:
    runs-on: ubuntu-latest
    name: close-issues
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v4
        with:
          # The message to post on the issue when tagging it. If none provided, will not mark issues stale.
          stale-issue-message: This issue has been marked as stale. If still relevent, the label can be removed.
          # The message to post on the issue when closing it. If none provided, will not comment when closing an issue.
          close-issue-message: Closed as stale. If needed, can be reopened
          # Only issues or pull requests with all of these labels are checked if stale. Defaults to `[]` (disabled) and can be a comma-separated list of labels.
          only-labels: "todo :spiral_notepad:"
