name: Delete temporary COMBINE/OMEX archives

on:
  schedule:
    - cron: '0 0 * * *' # daily
  workflow_dispatch:

jobs:
  delete:
    name: Delete temporary COMBINE/OMEX archives
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_ACCESS_TOKEN}}

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pip and setuptools
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools

      - name: Install requirements
        run: python -m pip install -r tools/delete-temporary-combine-archives/requirements.txt

      - name: Checkout configuration repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_ACCESS_TOKEN}}
          repository: biosimulations/deployment
          path: deployment
          submodules: "true"

      - name: Get configuration
        id: config
        run: |
          source deployment/config/dev/shared.env
          source deployment/secrets/dev/dispatch-service/secret.env

          HPC_SSH_PRIVATE_KEY=$(sed 's/\\n/\n/g' <<<"$HPC_SSH_PRIVATE_KEY")
          STORAGE_ENDPOINT=$(echo $STORAGE_ENDPOINT | cut -d '/' -f 3-)

          mkdir -p ~/.ssh
          chmod 0700 ~/.ssh
          echo "$HPC_SSH_PRIVATE_KEY" > ~/.ssh/id_hpc
          chmod 600 ~/.ssh/id_hpc
          ssh-keyscan -H ${HPC_SSH_HOST} >> ~/.ssh/known_hosts

          echo "::set-output name=HPC_SSH_HOST::$HPC_SSH_HOST"
          echo "::set-output name=HPC_SSH_USERNAME::$HPC_SSH_USERNAME"
          echo "::set-output name=STORAGE_ENDPOINT::$STORAGE_ENDPOINT"

      - name: Set up directory stucture for configuration
        run: |
          mkdir -p shared
          mkdir -p config
          mkdir -p secret

      # dev
      - name: Set up configuration for dev
        run: |
          cp deployment/config/dev/shared.env shared/shared.env
          cp deployment/config/dev/combine-api/config.env config/config.env
          cp deployment/secrets/dev/combine-api/secret.env secret/secret.env
          echo "STORAGE_ENDPOINT=https://localhost:4443" >> shared/shared.env

      - name: Delete temporary COMBINE/OMEX archives for dev
        env:
          PYTHONPATH: apps/combine-api
        run: |
          ssh -i ~/.ssh/id_hpc ${{ steps.config.outputs.HPC_SSH_USERNAME }}@${{ steps.config.outputs.HPC_SSH_HOST }} -L localhost:4443:${{ steps.config.outputs.STORAGE_ENDPOINT }}:443 &
          python tools/delete-temporary-combine-archives

      # prod
      - name: Set up configuration for prod
        run: |
          cp deployment/config/prod/shared.env shared/shared.env
          cp deployment/config/prod/combine-api/config.env config/config.env
          cp deployment/secrets/prod/combine-api/secret.env secret/secret.env
          echo "STORAGE_ENDPOINT=https://localhost:4443" >> shared/shared.env

      - name: Delete temporary COMBINE/OMEX archives for prod
        env:
          PYTHONPATH: apps/combine-api
        run: |
          ssh -i ~/.ssh/id_hpc ${{ steps.config.outputs.HPC_SSH_USERNAME }}@${{ steps.config.outputs.HPC_SSH_HOST }} -L localhost:4443:${{ steps.config.outputs.STORAGE_ENDPOINT }}:443 &
          python tools/delete-temporary-combine-archives
