name: Generate a report of the licenses of the dependencies
on:
  push:
    branches: [dev]
jobs:
  dependency-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"

      - name: Generate license report
        working-directory: ./biosimulations
        run: |
          npm install -g license-checker
          npm ci
          npm run gen-dependency-license-report

      - name: Commit Changes 
        uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
        with:
          author_name: Biosimulations-Daemon
          author_email: biosimulationsdaemon@gmail.com
          branch: dev
          message: 'Updated dependency licences'
          signoff: true
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN}} # Leave this line unchanged       
