name: Update documentation

on:
  release:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry==1.4.0

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install mkdocs python dependencies
        working-directory: ./docs
        run: poetry install

      - name: Build Docs
        if: ${{ github.event_name == 'pull_request' }}
        working-directory: ./docs
        run: poetry run mkdocs build

      - name: Deploy Docs
        if: ${{ github.event_name == 'release' || (github.event_name == 'push' && github.ref == 'refs/heads/dev')}}
        working-directory: ./docs
        run: poetry run mkdocs gh-deploy --force

