name: Documentation

on:
  push:
    branches:
      - master

jobs:
  Document:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Requirments
      run: npm install -g @compodoc/compodoc
    - name: Generate Dococumentation
      run: compodoc -p ./CRBM-Viz/tsconfig.json -d docs
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Created Automatic Documentation
        PULL_REQUEST_TITLE: 'Documentation '
        PULL_REQUEST_BODY: 'Created documentation using compodoc'
        PULL_REQUEST_LABELS: Documentation
        PULL_REQUEST_BRANCH: documentation
        PULL_REQUEST_ASSIGNEES: bilalshaikh42
        PULL_REQUEST_REVIEWERS: bilalshaikh42
        BRANCH_SUFFIX: none


