name: Update Documentation

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r docs/requirements.txt

      - name: Deploy Docs
        working-directory: ./docs
        run: mkdocs gh-deploy --force

