name: Format Source Code
on:
  workflow_dispatch:
   inputs:
    branch:
      required: true
      type: string
  workflow_call:
     inputs:
      branch:
        required: true
        type: string
     secrets:
      GH_ACCESS_TOKEN:
        required: true
      GPG_PRIVATE_KEY:
        required: true
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN}}
          ref:  ${{inputs.branch}}
      - name: Install Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: lts/fermium
          cache: npm


      - name: Install Nrwl CLI

        run: npm install -g @nrwl/cli


      - name: Install npm dependencies

        run: npm ci

      - name: Format files

        run: nx format --all

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit Changes
        uses: EndBug/add-and-commit@v7.5.0
        with:
          author_name: BioSimulations-Daemon
          author_email: biosimulationsdaemon@gmail.com
          branch: ${{inputs.branch}}
          message: 'chore: format files. [skip ci]'
          signoff: true
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}} # Leave this line unchanged
