# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo ${GITHUB_REF#refs/heads/}
        id: extract_branch
      # Change this to trigger the action in the deployment repo
      - name: Call Webhook
        env:
            GHCR_USERNAME: "${{ secrets.GHCR_USERNAME }}"
            GHCR_TOKEN: "${{ secrets.GHCR_TOKEN }}"
            BRANCH: ${{ steps.extract_branch.outputs.branch }}
        
        run: |
          curl --location --request POST 'https://api.github.com/repos/biosimulations/Biosimulations-Deployment/actions/workflows/deploy.yml/dispatches' --header 'Authorization: Bearer ${{secrets.GHCR_TOKEN}}' --header 'Content-Type: application/json' \
          --data-raw '{\"ref\": \"master\",
          \"inputs\":{
          \"overlay\": \"$BRANCH\",
          \"tag\": \"$GITHUB_SHA\"
          }}'
