name: Monitor todos

on:
  push:
    branches:
      - dev
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}

jobs:
  monitor:
    name: Monitor todos
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Create issues for new todos and close issues for removed todos"
        uses: alstr/todo-to-issue-action@v4.6.6
