name: Monitor todos

on: 
  push:
    branches:
      - dev

jobs:
  monitor:
    name: Monitor todos
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: "Create issues for new todos and close issues for removed todos"
        uses: alstr/todo-to-issue-action@v4.6.1
