name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        working-directory: ./biosimulations
        run: npm ci && npm install -g @nrwl/cli
      - name: Set Environment Variables
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            export NX_BASE=remotes/origin/$GITHUB_BASE_REF
          else
            export NX_BASE=$(git rev-parse HEAD~1)
          fi
      - name: Lint
        working-directory: ./biosimulations
        run: nx affected:lint --base=$NX_BASE
      - name: Build
        working-directory: ./biosimulations
        run: nx affected:build --base=$NX_BASE --prod
      - name: Test
        working-directory: ./biosimulations
        run: nx affected:test --base=$NX_BASE --code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: frontEnd
          file: ./biosimulations/coverage/apps/biosimulations-frontend/lcov.info
