name: CI

on:
  push:
  pull_request:
    branches: [master, stage, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - run: |
          git fetch --no-tags --prune --depth=5 origin master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "13.x"
      - name: Install dependencies
        working-directory: ./biosimulations
        run: npm ci && npm install -g @nrwl/cli

      - name: Set Environment Variables
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            export NX_BASE=remotes/origin/$GITHUB_BASE_REF
          else
            export NX_BASE=$(git rev-parse HEAD~1)
          fi
          echo $NX_BASE
      - name: Lint
        working-directory: ./biosimulations
        run: nx affected:lint --base=$NX_BASE

      - name: Build
        working-directory: ./biosimulations
        run: nx affected:build --base=$NX_BASE --prod
      - name: Test
        working-directory: ./biosimulations
        run: nx affected:test --base=$NX_BASE --code-coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          flags: frontEnd
          file: ./biosimulations/coverage/apps/biosimulations-frontend/lcov.info
