name: CI
on:
  push:
    branches:
      - dev
  pull_request:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  main:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [dev]
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'dev'

      - uses: actions/setup-node@v1 
        with: 
          node-version: '14'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - run: npx nx-cloud start-ci-run    
      - run: npx nx affected --target lint --parallel --max-parallel=9
        if: always()
      - run: npx nx affected --target=build --parallel --max-parallel=9
        if: always()
      - run: npx nx affected --target=test --parallel --max-parallel=9
        if: always()
      - run: npx nx-cloud stop-all-agents
        if: always()
  pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'origin/dev'
      - uses: actions/setup-node@v1
        with: 
          node-version: '14'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - run: npx nx-cloud start-ci-run
      - run: npx nx affected --target lint --parallel --max-parallel=9
        if: always()
      - run: npx nx affected --target=build --parallel --max-parallel=9
        if: always()
      - run: npx nx affected --target=test --parallel --max-parallel=9
        if: always()
      - run: npx nx-cloud stop-all-agents
        if: always()
  agents:
    runs-on: ubuntu-latest
    name: Agent 1
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14'
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get -y install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent  
