name: Release
on:
  workflow_dispatch:
  workflow_call:
   secrets:
     GH_RELEASE_TOKEN:
        required: true
     NPM_TOKEN:
        required: true
     GPG_PRIVATE_KEY:
        required: true
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_RELEASE_TOKEN}}
          ref: dev

      - name: Configure Git user
        run: |
          git config --global user.name 'BioSimulations-Daemon'
          git config --global user.email 'biosimulationsdaemon@gmail.com'

      - name: Install npm dependencies
        uses: bahmutov/npm-install@v1
        with:
          useRollingCache: true

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{secrets.GH_RELEASE_TOKEN}}
          GIT_CREDENTIALS: ${{secrets.GH_RELEASE_TOKEN}}
          GIT_AUTHOR_NAME: "BioSimulations-Daemon"
          GIT_AUTHOR_EMAIL: "biosimulationsdaemon@gmail.com"
          GIT_COMMITTER_NAME: "BioSimulations-Daemon"
          GIT_COMMITTER_EMAIL: "biosimulationsdaemon@gmail.com"
        run: npx semantic-release

      # Clean up changelog
      - name: Pull changes
        run: |
          git fetch --all
          git reset --hard origin/dev

      - name: Clean up changelog
        run: tools/clean-up-changelog

      - name: Commit changelog
        id: commit-changelog
        run: |
          set +e
          git add docs/CHANGELOG.md
          git commit -m "chore(release): cleaned up changelog [skip ci]"
          if [[ $? = 0 ]]; then
            changed=1
          else
            changed=0
          fi
          echo "::set-output name=changed::$changed"

      - name: Push the updated changelog
        if: steps.commit-changelog.outputs.changed == '1'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
