name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@v4.2.0
        with:
          validateSingleCommit: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  lint-commits:
    name: Lint Commits    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bilalshaikh42/action-conventional-commits@v2.0.1
