name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # Please look up the latest version from
      # https://github.com/amannn/action-semantic-pull-request/releases
      - uses: amannn/action-semantic-pull-request@3.4.2
        with:
          validateSingleCommit: true
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
