name: Check spelling
on:
  pull_request:
  push:
  issue_comment:
    types: [created]
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}

jobs:
  spelling:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - name: checkout-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: actions/checkout@v2
      with:
        ref: refs/pull/${{github.event.pull_request.number}}/merge
    - name: checkout
      if: ${{ github.event_name == 'push' ||
        (
          contains(github.event.comment.body, '@check-spelling-bot apply')
        ) }}
      uses: actions/checkout@v2
    # Debugging before check-spelling action
    - name: Debug before check-spelling
      if: ${{ github.event_name != 'issue_comment' ||
        (
        contains(github.event.comment.body, '@check-spelling-bot apply')
        ) }}
      run: |
        echo "Debugging information before check-spelling action"
        df -h # Check disk space
        free -m # Check memory usage
        ps aux # Check running processes
        df -i # Check inode exhaustion
        pwd && ls -alh
    - uses: check-spelling/check-spelling@v0.0.22
      id: spelling
      if: ${{ github.event_name != 'issue_comment' ||
        (
          contains(github.event.comment.body, '@check-spelling-bot apply')
        ) }}
      with:
       suppress_push_for_open_pull_request: 1
