name: Test simulation functionality
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}

jobs:
  testSimulations:
    name: Run example simulations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"

      - name: Install requirements
        run: python -m pip install -r tools/submit-example-simulation-runs.requirements.txt

      - name: Run test against API
        run: |
          ./tools/submit-example-simulation-runs \
            --runbiosimulations-deployment org \
            --biosimulators-deployment org \
            --test true \
            --example "Repressilator (Elowitz & Leibler, Nature, 2000; SBML; CVODE; tellurium)"
  sendHeartbeat:
    name: Send Success Hearbeat
    needs: testSimulations
    runs-on: ubuntu-latest
    steps:
        - if: ${{ success() }}
          run: curl ${{secrets.SIMULATIONS_HEARTBEAT}}
