name: Ontology Update
on:
  schedule:
    - cron: '0 0 * * 0' # weekly

  workflow_dispatch:
    inputs:
      ontologies:
        description: 'Comma-separated list of the names of ontologies to update; default: update each ontology'
        required: false
        default: ''

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          token: ${{ secrets.GH_ACCESS_TOKEN}}

      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends wget

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install Python packages
        run: |
          python -m pip install -r ${GITHUB_WORKSPACE}/biosimulations/tools/generate-ontologies-requirements.txt

      - name: Update ontologies
        run: ${GITHUB_WORKSPACE}/biosimulations/tools/generate-ontologies ${{ github.event.inputs.ontologies }}
        
      - name: Commit Changes 
        uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
        with:
          author_name: Biosimulations-Daemon
          author_email: biosimulationsdaemon@gmail.com
          branch: dev
          message: 'Updated Ontologies'
          signoff: true
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN}} # Leave this line unchanged   
