name: Validate OpenAPI specifications

on:
  push:
    paths:
      - "apps/combine-api/combine_api/spec/spec.yml"
      - "apps/simdata-api/simdata_api/spec/openapi.yaml"
      # - "apps/api/**"
      # - "apps/account-api/**"
      # - "apps/simulators-api/**"
      # - "apps/simulators-api/**"
      # - "libs/datamodel/api/**"

  schedule:
    - cron: '0 0 * * 0' # weekly

  workflow_dispatch:

env:
  NX_SKIP_NX_CACHE: ${{ vars.NX_SKIP_NX_CACHE_VALUE }}


jobs:
  test-apis:
    runs-on: ubuntu-latest
    name: Test APIs

    strategy:
      fail-fast: false
      matrix:
        apiSpecs:
          - https://api.biosimulations.dev/openapi.json
          - https://api.biosimulators.dev/openapi.json
          - apps/combine-api/combine_api/spec/spec.yml
          - apps/simdata-api/simdata_api/spec/openapi.yaml

    steps:
      - name: Checkout repository
        if: "!startsWith(matrix.apiSpecs, 'https://')"
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Download API specifications
        if: "startsWith(matrix.apiSpecs, 'https://')"
        run: curl ${{ matrix.apiSpecs }} -o openapi.json --retry 5 --retry-delay 30

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.3.2
        if: "!startsWith(matrix.apiSpecs, 'https://')"
        with:
          definition-file: ${{ matrix.apiSpecs }}

      - name: Validate OpenAPI definition
        uses: char0n/swagger-editor-validate@v1.3.2
        if: "startsWith(matrix.apiSpecs, 'https://')"
        with:
          definition-file: openapi.json
